//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinaleProjetSeke.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployesSupprime
    {
        public string CodeEmployes { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Rue { get; set; }
        public string Ville { get; set; }
        public string Province { get; set; }
        public Nullable<int> Statut { get; set; }
        public string Photo { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DateSuppression { get; set; }
        public string MotifSuppression { get; set; }
        public Nullable<System.DateTime> DateEmbauche { get; set; }
    }
}
