//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinaleProjetSeke.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class location
    {
        public string CodeProduit { get; set; }
        public string Code { get; set; }
        public System.DateTime DateLocation { get; set; }
        public Nullable<System.DateTime> DateRetour { get; set; }
        public string CodeEmployes { get; set; }
        public Nullable<double> PrixLocation { get; set; }
        public Nullable<int> QuantiteLocation { get; set; }
        public Nullable<decimal> Rabais { get; set; }
    
        public virtual Employe Employe { get; set; }
        public virtual Produit Produit { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
