//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinaleProjetSeke.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SekeDATAEntities : DbContext
    {
        public SekeDATAEntities()
            : base("name=SekeDATAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employe> Employes { get; set; }
        public virtual DbSet<location> locations { get; set; }
        public virtual DbSet<Produit> Produits { get; set; }
        public virtual DbSet<Reservation> Reservations { get; set; }
        public virtual DbSet<Utilisateur> Utilisateurs { get; set; }
        public virtual DbSet<Vente> Ventes { get; set; }
        public virtual DbSet<EmployesSupprime> EmployesSupprimes { get; set; }
        public virtual DbSet<ProduitSupprime> ProduitSupprimes { get; set; }
        public virtual DbSet<UtilisateurSupprime> UtilisateurSupprimes { get; set; }
    }
}
