//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinaleProjetSeke.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProduitSupprime
    {
        public string CodeProduit { get; set; }
        public string Nom { get; set; }
        public Nullable<double> PrixAchat { get; set; }
        public Nullable<int> QuantiteStock { get; set; }
        public string Photo { get; set; }
        public Nullable<decimal> Note { get; set; }
        public Nullable<decimal> RabaisVente { get; set; }
        public Nullable<decimal> RabaisLocation { get; set; }
        public Nullable<System.DateTime> DateSortie { get; set; }
    }
}
