#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinaleProjetSeke
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SekeDATA")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Définitions de méthodes d'extensibilité
    partial void OnCreated();
    partial void InsertUtilisateur(Utilisateur instance);
    partial void UpdateUtilisateur(Utilisateur instance);
    partial void DeleteUtilisateur(Utilisateur instance);
    partial void InsertEmploye(Employe instance);
    partial void UpdateEmploye(Employe instance);
    partial void DeleteEmploye(Employe instance);
    partial void InsertReservation(Reservation instance);
    partial void UpdateReservation(Reservation instance);
    partial void DeleteReservation(Reservation instance);
    partial void InsertAdmin(Admin instance);
    partial void UpdateAdmin(Admin instance);
    partial void DeleteAdmin(Admin instance);
    partial void Insertlocation(location instance);
    partial void Updatelocation(location instance);
    partial void Deletelocation(location instance);
    partial void InsertProduit(Produit instance);
    partial void UpdateProduit(Produit instance);
    partial void DeleteProduit(Produit instance);
    partial void InsertVente(Vente instance);
    partial void UpdateVente(Vente instance);
    partial void DeleteVente(Vente instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SekeDATAConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<EmployesSupprime> EmployesSupprimes
		{
			get
			{
				return this.GetTable<EmployesSupprime>();
			}
		}
		
		public System.Data.Linq.Table<UtilisateurSupprime> UtilisateurSupprimes
		{
			get
			{
				return this.GetTable<UtilisateurSupprime>();
			}
		}
		
		public System.Data.Linq.Table<Utilisateur> Utilisateurs
		{
			get
			{
				return this.GetTable<Utilisateur>();
			}
		}
		
		public System.Data.Linq.Table<Employe> Employes
		{
			get
			{
				return this.GetTable<Employe>();
			}
		}
		
		public System.Data.Linq.Table<Reservation> Reservations
		{
			get
			{
				return this.GetTable<Reservation>();
			}
		}
		
		public System.Data.Linq.Table<Admin> Admins
		{
			get
			{
				return this.GetTable<Admin>();
			}
		}
		
		public System.Data.Linq.Table<ProduitSupprime> ProduitSupprimes
		{
			get
			{
				return this.GetTable<ProduitSupprime>();
			}
		}
		
		public System.Data.Linq.Table<location> location
		{
			get
			{
				return this.GetTable<location>();
			}
		}
		
		public System.Data.Linq.Table<Produit> Produit
		{
			get
			{
				return this.GetTable<Produit>();
			}
		}
		
		public System.Data.Linq.Table<Vente> Vente
		{
			get
			{
				return this.GetTable<Vente>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EmployesSupprimes")]
	public partial class EmployesSupprime
	{
		
		private string _CodeEmployes;
		
		private string _Nom;
		
		private string _Prenom;
		
		private string _Rue;
		
		private string _Ville;
		
		private string _Province;
		
		private System.Nullable<int> _Statut;
		
		private string _Photo;
		
		private string _Email;
		
		private System.Nullable<System.DateTime> _DateSuppression;
		
		private string _MotifSuppression;
		
		private System.Nullable<System.DateTime> _DateEmbauche;
		
		public EmployesSupprime()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeEmployes", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CodeEmployes
		{
			get
			{
				return this._CodeEmployes;
			}
			set
			{
				if ((this._CodeEmployes != value))
				{
					this._CodeEmployes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom", DbType="NVarChar(50)")]
		public string Nom
		{
			get
			{
				return this._Nom;
			}
			set
			{
				if ((this._Nom != value))
				{
					this._Nom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prenom", DbType="NVarChar(50)")]
		public string Prenom
		{
			get
			{
				return this._Prenom;
			}
			set
			{
				if ((this._Prenom != value))
				{
					this._Prenom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rue", DbType="NVarChar(50)")]
		public string Rue
		{
			get
			{
				return this._Rue;
			}
			set
			{
				if ((this._Rue != value))
				{
					this._Rue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ville", DbType="NVarChar(50)")]
		public string Ville
		{
			get
			{
				return this._Ville;
			}
			set
			{
				if ((this._Ville != value))
				{
					this._Ville = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Province", DbType="NVarChar(50)")]
		public string Province
		{
			get
			{
				return this._Province;
			}
			set
			{
				if ((this._Province != value))
				{
					this._Province = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Statut", DbType="Int")]
		public System.Nullable<int> Statut
		{
			get
			{
				return this._Statut;
			}
			set
			{
				if ((this._Statut != value))
				{
					this._Statut = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Photo", DbType="NVarChar(50)")]
		public string Photo
		{
			get
			{
				return this._Photo;
			}
			set
			{
				if ((this._Photo != value))
				{
					this._Photo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateSuppression", DbType="Date")]
		public System.Nullable<System.DateTime> DateSuppression
		{
			get
			{
				return this._DateSuppression;
			}
			set
			{
				if ((this._DateSuppression != value))
				{
					this._DateSuppression = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MotifSuppression", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string MotifSuppression
		{
			get
			{
				return this._MotifSuppression;
			}
			set
			{
				if ((this._MotifSuppression != value))
				{
					this._MotifSuppression = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateEmbauche", DbType="Date")]
		public System.Nullable<System.DateTime> DateEmbauche
		{
			get
			{
				return this._DateEmbauche;
			}
			set
			{
				if ((this._DateEmbauche != value))
				{
					this._DateEmbauche = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UtilisateurSupprimes")]
	public partial class UtilisateurSupprime
	{
		
		private string _Code;
		
		private string _Nom;
		
		private string _Prenom;
		
		private string _Rue;
		
		private string _Ville;
		
		private string _Province;
		
		private System.Nullable<int> _Statut;
		
		private string _Photo;
		
		private string _Email;
		
		private string _MotifSuppression;
		
		private System.Nullable<System.DateTime> _DateSuppression;
		
		public UtilisateurSupprime()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom", DbType="NVarChar(50)")]
		public string Nom
		{
			get
			{
				return this._Nom;
			}
			set
			{
				if ((this._Nom != value))
				{
					this._Nom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prenom", DbType="NVarChar(50)")]
		public string Prenom
		{
			get
			{
				return this._Prenom;
			}
			set
			{
				if ((this._Prenom != value))
				{
					this._Prenom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rue", DbType="NVarChar(50)")]
		public string Rue
		{
			get
			{
				return this._Rue;
			}
			set
			{
				if ((this._Rue != value))
				{
					this._Rue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ville", DbType="NVarChar(50)")]
		public string Ville
		{
			get
			{
				return this._Ville;
			}
			set
			{
				if ((this._Ville != value))
				{
					this._Ville = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Province", DbType="NVarChar(50)")]
		public string Province
		{
			get
			{
				return this._Province;
			}
			set
			{
				if ((this._Province != value))
				{
					this._Province = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Statut", DbType="Int")]
		public System.Nullable<int> Statut
		{
			get
			{
				return this._Statut;
			}
			set
			{
				if ((this._Statut != value))
				{
					this._Statut = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Photo", DbType="NVarChar(50)")]
		public string Photo
		{
			get
			{
				return this._Photo;
			}
			set
			{
				if ((this._Photo != value))
				{
					this._Photo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MotifSuppression", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string MotifSuppression
		{
			get
			{
				return this._MotifSuppression;
			}
			set
			{
				if ((this._MotifSuppression != value))
				{
					this._MotifSuppression = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateSuppression", DbType="Date")]
		public System.Nullable<System.DateTime> DateSuppression
		{
			get
			{
				return this._DateSuppression;
			}
			set
			{
				if ((this._DateSuppression != value))
				{
					this._DateSuppression = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Utilisateur")]
	public partial class Utilisateur : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Code;
		
		private string _Nom;
		
		private string _Prenom;
		
		private string _Rue;
		
		private string _Ville;
		
		private string _Province;
		
		private System.Nullable<int> _Statut;
		
		private string _Photo;
		
		private string _Email;
		
		private string _MotifSuppression;
		
		private System.Nullable<System.DateTime> _DateSuppression;
		
		private string _password;
		
		private EntitySet<Reservation> _Reservations;
		
		private EntitySet<location> _location;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnNomChanging(string value);
    partial void OnNomChanged();
    partial void OnPrenomChanging(string value);
    partial void OnPrenomChanged();
    partial void OnRueChanging(string value);
    partial void OnRueChanged();
    partial void OnVilleChanging(string value);
    partial void OnVilleChanged();
    partial void OnProvinceChanging(string value);
    partial void OnProvinceChanged();
    partial void OnStatutChanging(System.Nullable<int> value);
    partial void OnStatutChanged();
    partial void OnPhotoChanging(string value);
    partial void OnPhotoChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnMotifSuppressionChanging(string value);
    partial void OnMotifSuppressionChanged();
    partial void OnDateSuppressionChanging(System.Nullable<System.DateTime> value);
    partial void OnDateSuppressionChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    #endregion
		
		public Utilisateur()
		{
			this._Reservations = new EntitySet<Reservation>(new Action<Reservation>(this.attach_Reservations), new Action<Reservation>(this.detach_Reservations));
			this._location = new EntitySet<location>(new Action<location>(this.attach_location), new Action<location>(this.detach_location));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom", DbType="NVarChar(50)")]
		public string Nom
		{
			get
			{
				return this._Nom;
			}
			set
			{
				if ((this._Nom != value))
				{
					this.OnNomChanging(value);
					this.SendPropertyChanging();
					this._Nom = value;
					this.SendPropertyChanged("Nom");
					this.OnNomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prenom", DbType="NVarChar(50)")]
		public string Prenom
		{
			get
			{
				return this._Prenom;
			}
			set
			{
				if ((this._Prenom != value))
				{
					this.OnPrenomChanging(value);
					this.SendPropertyChanging();
					this._Prenom = value;
					this.SendPropertyChanged("Prenom");
					this.OnPrenomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rue", DbType="NVarChar(50)")]
		public string Rue
		{
			get
			{
				return this._Rue;
			}
			set
			{
				if ((this._Rue != value))
				{
					this.OnRueChanging(value);
					this.SendPropertyChanging();
					this._Rue = value;
					this.SendPropertyChanged("Rue");
					this.OnRueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ville", DbType="NVarChar(50)")]
		public string Ville
		{
			get
			{
				return this._Ville;
			}
			set
			{
				if ((this._Ville != value))
				{
					this.OnVilleChanging(value);
					this.SendPropertyChanging();
					this._Ville = value;
					this.SendPropertyChanged("Ville");
					this.OnVilleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Province", DbType="NVarChar(50)")]
		public string Province
		{
			get
			{
				return this._Province;
			}
			set
			{
				if ((this._Province != value))
				{
					this.OnProvinceChanging(value);
					this.SendPropertyChanging();
					this._Province = value;
					this.SendPropertyChanged("Province");
					this.OnProvinceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Statut", DbType="Int")]
		public System.Nullable<int> Statut
		{
			get
			{
				return this._Statut;
			}
			set
			{
				if ((this._Statut != value))
				{
					this.OnStatutChanging(value);
					this.SendPropertyChanging();
					this._Statut = value;
					this.SendPropertyChanged("Statut");
					this.OnStatutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Photo", DbType="NVarChar(50)")]
		public string Photo
		{
			get
			{
				return this._Photo;
			}
			set
			{
				if ((this._Photo != value))
				{
					this.OnPhotoChanging(value);
					this.SendPropertyChanging();
					this._Photo = value;
					this.SendPropertyChanged("Photo");
					this.OnPhotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MotifSuppression", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string MotifSuppression
		{
			get
			{
				return this._MotifSuppression;
			}
			set
			{
				if ((this._MotifSuppression != value))
				{
					this.OnMotifSuppressionChanging(value);
					this.SendPropertyChanging();
					this._MotifSuppression = value;
					this.SendPropertyChanged("MotifSuppression");
					this.OnMotifSuppressionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateSuppression", DbType="Date")]
		public System.Nullable<System.DateTime> DateSuppression
		{
			get
			{
				return this._DateSuppression;
			}
			set
			{
				if ((this._DateSuppression != value))
				{
					this.OnDateSuppressionChanging(value);
					this.SendPropertyChanging();
					this._DateSuppression = value;
					this.SendPropertyChanged("DateSuppression");
					this.OnDateSuppressionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Utilisateur_Reservation", Storage="_Reservations", ThisKey="Code", OtherKey="Code")]
		public EntitySet<Reservation> Reservations
		{
			get
			{
				return this._Reservations;
			}
			set
			{
				this._Reservations.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Utilisateur_location", Storage="_location", ThisKey="Code", OtherKey="Code")]
		public EntitySet<location> location
		{
			get
			{
				return this._location;
			}
			set
			{
				this._location.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Reservations(Reservation entity)
		{
			this.SendPropertyChanging();
			entity.Utilisateur = this;
		}
		
		private void detach_Reservations(Reservation entity)
		{
			this.SendPropertyChanging();
			entity.Utilisateur = null;
		}
		
		private void attach_location(location entity)
		{
			this.SendPropertyChanging();
			entity.Utilisateur = this;
		}
		
		private void detach_location(location entity)
		{
			this.SendPropertyChanging();
			entity.Utilisateur = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Employes")]
	public partial class Employe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CodeEmployes;
		
		private string _Nom;
		
		private string _Prenom;
		
		private string _Rue;
		
		private string _Ville;
		
		private string _Province;
		
		private System.Nullable<int> _Statut;
		
		private string _Photo;
		
		private string _Email;
		
		private System.Nullable<System.DateTime> _DateSuppression;
		
		private string _MotifSuppression;
		
		private System.Nullable<System.DateTime> _DateEmbauche;
		
		private string _password;
		
		private EntitySet<Reservation> _Reservations;
		
		private EntitySet<location> _location;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeEmployesChanging(string value);
    partial void OnCodeEmployesChanged();
    partial void OnNomChanging(string value);
    partial void OnNomChanged();
    partial void OnPrenomChanging(string value);
    partial void OnPrenomChanged();
    partial void OnRueChanging(string value);
    partial void OnRueChanged();
    partial void OnVilleChanging(string value);
    partial void OnVilleChanged();
    partial void OnProvinceChanging(string value);
    partial void OnProvinceChanged();
    partial void OnStatutChanging(System.Nullable<int> value);
    partial void OnStatutChanged();
    partial void OnPhotoChanging(string value);
    partial void OnPhotoChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDateSuppressionChanging(System.Nullable<System.DateTime> value);
    partial void OnDateSuppressionChanged();
    partial void OnMotifSuppressionChanging(string value);
    partial void OnMotifSuppressionChanged();
    partial void OnDateEmbaucheChanging(System.Nullable<System.DateTime> value);
    partial void OnDateEmbaucheChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    #endregion
		
		public Employe()
		{
			this._Reservations = new EntitySet<Reservation>(new Action<Reservation>(this.attach_Reservations), new Action<Reservation>(this.detach_Reservations));
			this._location = new EntitySet<location>(new Action<location>(this.attach_location), new Action<location>(this.detach_location));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeEmployes", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodeEmployes
		{
			get
			{
				return this._CodeEmployes;
			}
			set
			{
				if ((this._CodeEmployes != value))
				{
					this.OnCodeEmployesChanging(value);
					this.SendPropertyChanging();
					this._CodeEmployes = value;
					this.SendPropertyChanged("CodeEmployes");
					this.OnCodeEmployesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom", DbType="NVarChar(50)")]
		public string Nom
		{
			get
			{
				return this._Nom;
			}
			set
			{
				if ((this._Nom != value))
				{
					this.OnNomChanging(value);
					this.SendPropertyChanging();
					this._Nom = value;
					this.SendPropertyChanged("Nom");
					this.OnNomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prenom", DbType="NVarChar(50)")]
		public string Prenom
		{
			get
			{
				return this._Prenom;
			}
			set
			{
				if ((this._Prenom != value))
				{
					this.OnPrenomChanging(value);
					this.SendPropertyChanging();
					this._Prenom = value;
					this.SendPropertyChanged("Prenom");
					this.OnPrenomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rue", DbType="NVarChar(50)")]
		public string Rue
		{
			get
			{
				return this._Rue;
			}
			set
			{
				if ((this._Rue != value))
				{
					this.OnRueChanging(value);
					this.SendPropertyChanging();
					this._Rue = value;
					this.SendPropertyChanged("Rue");
					this.OnRueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ville", DbType="NVarChar(50)")]
		public string Ville
		{
			get
			{
				return this._Ville;
			}
			set
			{
				if ((this._Ville != value))
				{
					this.OnVilleChanging(value);
					this.SendPropertyChanging();
					this._Ville = value;
					this.SendPropertyChanged("Ville");
					this.OnVilleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Province", DbType="NVarChar(50)")]
		public string Province
		{
			get
			{
				return this._Province;
			}
			set
			{
				if ((this._Province != value))
				{
					this.OnProvinceChanging(value);
					this.SendPropertyChanging();
					this._Province = value;
					this.SendPropertyChanged("Province");
					this.OnProvinceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Statut", DbType="Int")]
		public System.Nullable<int> Statut
		{
			get
			{
				return this._Statut;
			}
			set
			{
				if ((this._Statut != value))
				{
					this.OnStatutChanging(value);
					this.SendPropertyChanging();
					this._Statut = value;
					this.SendPropertyChanged("Statut");
					this.OnStatutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Photo", DbType="NVarChar(50)")]
		public string Photo
		{
			get
			{
				return this._Photo;
			}
			set
			{
				if ((this._Photo != value))
				{
					this.OnPhotoChanging(value);
					this.SendPropertyChanging();
					this._Photo = value;
					this.SendPropertyChanged("Photo");
					this.OnPhotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateSuppression", DbType="Date")]
		public System.Nullable<System.DateTime> DateSuppression
		{
			get
			{
				return this._DateSuppression;
			}
			set
			{
				if ((this._DateSuppression != value))
				{
					this.OnDateSuppressionChanging(value);
					this.SendPropertyChanging();
					this._DateSuppression = value;
					this.SendPropertyChanged("DateSuppression");
					this.OnDateSuppressionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MotifSuppression", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string MotifSuppression
		{
			get
			{
				return this._MotifSuppression;
			}
			set
			{
				if ((this._MotifSuppression != value))
				{
					this.OnMotifSuppressionChanging(value);
					this.SendPropertyChanging();
					this._MotifSuppression = value;
					this.SendPropertyChanged("MotifSuppression");
					this.OnMotifSuppressionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateEmbauche", DbType="Date")]
		public System.Nullable<System.DateTime> DateEmbauche
		{
			get
			{
				return this._DateEmbauche;
			}
			set
			{
				if ((this._DateEmbauche != value))
				{
					this.OnDateEmbaucheChanging(value);
					this.SendPropertyChanging();
					this._DateEmbauche = value;
					this.SendPropertyChanged("DateEmbauche");
					this.OnDateEmbaucheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Employe_Reservation", Storage="_Reservations", ThisKey="CodeEmployes", OtherKey="CodeEmployes")]
		public EntitySet<Reservation> Reservations
		{
			get
			{
				return this._Reservations;
			}
			set
			{
				this._Reservations.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Employe_location", Storage="_location", ThisKey="CodeEmployes", OtherKey="CodeEmployes")]
		public EntitySet<location> location
		{
			get
			{
				return this._location;
			}
			set
			{
				this._location.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Reservations(Reservation entity)
		{
			this.SendPropertyChanging();
			entity.Employe = this;
		}
		
		private void detach_Reservations(Reservation entity)
		{
			this.SendPropertyChanging();
			entity.Employe = null;
		}
		
		private void attach_location(location entity)
		{
			this.SendPropertyChanging();
			entity.Employe = this;
		}
		
		private void detach_location(location entity)
		{
			this.SendPropertyChanging();
			entity.Employe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Reservation")]
	public partial class Reservation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _NumeroR;
		
		private string _Nom;
		
		private string _Telephone;
		
		private string _Adresse;
		
		private string _Msg;
		
		private string _Code;
		
		private System.DateTime _DateReservation;
		
		private System.Nullable<System.DateTime> _DateRetour;
		
		private System.Nullable<System.DateTime> _DateRecuperation;
		
		private string _NumeroCard;
		
		private string _NomProduit;
		
		private string _CodeEmployes;
		
		private System.Nullable<double> _PrixReserve;
		
		private System.Nullable<double> _QuantiteReserve;
		
		private System.Nullable<double> _Montant;
		
		private System.Nullable<double> _Taxe;
		
		private System.Nullable<double> _Ttc;
		
		private System.Nullable<double> _Rabais;
		
		private string _CodeProduit;
		
		private EntityRef<Employe> _Employe;
		
		private EntityRef<Utilisateur> _Utilisateur;
		
		private EntityRef<Produit> _Produit;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNumeroRChanging(string value);
    partial void OnNumeroRChanged();
    partial void OnNomChanging(string value);
    partial void OnNomChanged();
    partial void OnTelephoneChanging(string value);
    partial void OnTelephoneChanged();
    partial void OnAdresseChanging(string value);
    partial void OnAdresseChanged();
    partial void OnMsgChanging(string value);
    partial void OnMsgChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnDateReservationChanging(System.DateTime value);
    partial void OnDateReservationChanged();
    partial void OnDateRetourChanging(System.Nullable<System.DateTime> value);
    partial void OnDateRetourChanged();
    partial void OnDateRecuperationChanging(System.Nullable<System.DateTime> value);
    partial void OnDateRecuperationChanged();
    partial void OnNumeroCardChanging(string value);
    partial void OnNumeroCardChanged();
    partial void OnNomProduitChanging(string value);
    partial void OnNomProduitChanged();
    partial void OnCodeEmployesChanging(string value);
    partial void OnCodeEmployesChanged();
    partial void OnPrixReserveChanging(System.Nullable<double> value);
    partial void OnPrixReserveChanged();
    partial void OnQuantiteReserveChanging(System.Nullable<double> value);
    partial void OnQuantiteReserveChanged();
    partial void OnMontantChanging(System.Nullable<double> value);
    partial void OnMontantChanged();
    partial void OnTaxeChanging(System.Nullable<double> value);
    partial void OnTaxeChanged();
    partial void OnTtcChanging(System.Nullable<double> value);
    partial void OnTtcChanged();
    partial void OnRabaisChanging(System.Nullable<double> value);
    partial void OnRabaisChanged();
    partial void OnCodeProduitChanging(string value);
    partial void OnCodeProduitChanged();
    #endregion
		
		public Reservation()
		{
			this._Employe = default(EntityRef<Employe>);
			this._Utilisateur = default(EntityRef<Utilisateur>);
			this._Produit = default(EntityRef<Produit>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroR", DbType="NVarChar(53) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string NumeroR
		{
			get
			{
				return this._NumeroR;
			}
			set
			{
				if ((this._NumeroR != value))
				{
					this.OnNumeroRChanging(value);
					this.SendPropertyChanging();
					this._NumeroR = value;
					this.SendPropertyChanged("NumeroR");
					this.OnNumeroRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom", DbType="VarChar(50)")]
		public string Nom
		{
			get
			{
				return this._Nom;
			}
			set
			{
				if ((this._Nom != value))
				{
					this.OnNomChanging(value);
					this.SendPropertyChanging();
					this._Nom = value;
					this.SendPropertyChanged("Nom");
					this.OnNomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telephone", DbType="VarChar(50)")]
		public string Telephone
		{
			get
			{
				return this._Telephone;
			}
			set
			{
				if ((this._Telephone != value))
				{
					this.OnTelephoneChanging(value);
					this.SendPropertyChanging();
					this._Telephone = value;
					this.SendPropertyChanged("Telephone");
					this.OnTelephoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adresse", DbType="VarChar(50)")]
		public string Adresse
		{
			get
			{
				return this._Adresse;
			}
			set
			{
				if ((this._Adresse != value))
				{
					this.OnAdresseChanging(value);
					this.SendPropertyChanging();
					this._Adresse = value;
					this.SendPropertyChanged("Adresse");
					this.OnAdresseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Msg", DbType="VarChar(100)")]
		public string Msg
		{
			get
			{
				return this._Msg;
			}
			set
			{
				if ((this._Msg != value))
				{
					this.OnMsgChanging(value);
					this.SendPropertyChanging();
					this._Msg = value;
					this.SendPropertyChanged("Msg");
					this.OnMsgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					if (this._Utilisateur.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateReservation", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime DateReservation
		{
			get
			{
				return this._DateReservation;
			}
			set
			{
				if ((this._DateReservation != value))
				{
					this.OnDateReservationChanging(value);
					this.SendPropertyChanging();
					this._DateReservation = value;
					this.SendPropertyChanged("DateReservation");
					this.OnDateReservationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateRetour", DbType="Date")]
		public System.Nullable<System.DateTime> DateRetour
		{
			get
			{
				return this._DateRetour;
			}
			set
			{
				if ((this._DateRetour != value))
				{
					this.OnDateRetourChanging(value);
					this.SendPropertyChanging();
					this._DateRetour = value;
					this.SendPropertyChanged("DateRetour");
					this.OnDateRetourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateRecuperation", DbType="Date")]
		public System.Nullable<System.DateTime> DateRecuperation
		{
			get
			{
				return this._DateRecuperation;
			}
			set
			{
				if ((this._DateRecuperation != value))
				{
					this.OnDateRecuperationChanging(value);
					this.SendPropertyChanging();
					this._DateRecuperation = value;
					this.SendPropertyChanged("DateRecuperation");
					this.OnDateRecuperationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroCard", DbType="NVarChar(MAX)")]
		public string NumeroCard
		{
			get
			{
				return this._NumeroCard;
			}
			set
			{
				if ((this._NumeroCard != value))
				{
					this.OnNumeroCardChanging(value);
					this.SendPropertyChanging();
					this._NumeroCard = value;
					this.SendPropertyChanged("NumeroCard");
					this.OnNumeroCardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomProduit", DbType="NVarChar(50)")]
		public string NomProduit
		{
			get
			{
				return this._NomProduit;
			}
			set
			{
				if ((this._NomProduit != value))
				{
					this.OnNomProduitChanging(value);
					this.SendPropertyChanging();
					this._NomProduit = value;
					this.SendPropertyChanged("NomProduit");
					this.OnNomProduitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeEmployes", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodeEmployes
		{
			get
			{
				return this._CodeEmployes;
			}
			set
			{
				if ((this._CodeEmployes != value))
				{
					if (this._Employe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodeEmployesChanging(value);
					this.SendPropertyChanging();
					this._CodeEmployes = value;
					this.SendPropertyChanged("CodeEmployes");
					this.OnCodeEmployesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrixReserve", DbType="Float")]
		public System.Nullable<double> PrixReserve
		{
			get
			{
				return this._PrixReserve;
			}
			set
			{
				if ((this._PrixReserve != value))
				{
					this.OnPrixReserveChanging(value);
					this.SendPropertyChanging();
					this._PrixReserve = value;
					this.SendPropertyChanged("PrixReserve");
					this.OnPrixReserveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuantiteReserve", DbType="Float")]
		public System.Nullable<double> QuantiteReserve
		{
			get
			{
				return this._QuantiteReserve;
			}
			set
			{
				if ((this._QuantiteReserve != value))
				{
					this.OnQuantiteReserveChanging(value);
					this.SendPropertyChanging();
					this._QuantiteReserve = value;
					this.SendPropertyChanged("QuantiteReserve");
					this.OnQuantiteReserveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Montant", DbType="Float")]
		public System.Nullable<double> Montant
		{
			get
			{
				return this._Montant;
			}
			set
			{
				if ((this._Montant != value))
				{
					this.OnMontantChanging(value);
					this.SendPropertyChanging();
					this._Montant = value;
					this.SendPropertyChanged("Montant");
					this.OnMontantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Taxe", DbType="Float")]
		public System.Nullable<double> Taxe
		{
			get
			{
				return this._Taxe;
			}
			set
			{
				if ((this._Taxe != value))
				{
					this.OnTaxeChanging(value);
					this.SendPropertyChanging();
					this._Taxe = value;
					this.SendPropertyChanged("Taxe");
					this.OnTaxeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ttc", DbType="Float")]
		public System.Nullable<double> Ttc
		{
			get
			{
				return this._Ttc;
			}
			set
			{
				if ((this._Ttc != value))
				{
					this.OnTtcChanging(value);
					this.SendPropertyChanging();
					this._Ttc = value;
					this.SendPropertyChanged("Ttc");
					this.OnTtcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rabais", DbType="Float")]
		public System.Nullable<double> Rabais
		{
			get
			{
				return this._Rabais;
			}
			set
			{
				if ((this._Rabais != value))
				{
					this.OnRabaisChanging(value);
					this.SendPropertyChanging();
					this._Rabais = value;
					this.SendPropertyChanged("Rabais");
					this.OnRabaisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeProduit", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodeProduit
		{
			get
			{
				return this._CodeProduit;
			}
			set
			{
				if ((this._CodeProduit != value))
				{
					if (this._Produit.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodeProduitChanging(value);
					this.SendPropertyChanging();
					this._CodeProduit = value;
					this.SendPropertyChanged("CodeProduit");
					this.OnCodeProduitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Employe_Reservation", Storage="_Employe", ThisKey="CodeEmployes", OtherKey="CodeEmployes", IsForeignKey=true)]
		public Employe Employe
		{
			get
			{
				return this._Employe.Entity;
			}
			set
			{
				Employe previousValue = this._Employe.Entity;
				if (((previousValue != value) 
							|| (this._Employe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Employe.Entity = null;
						previousValue.Reservations.Remove(this);
					}
					this._Employe.Entity = value;
					if ((value != null))
					{
						value.Reservations.Add(this);
						this._CodeEmployes = value.CodeEmployes;
					}
					else
					{
						this._CodeEmployes = default(string);
					}
					this.SendPropertyChanged("Employe");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Utilisateur_Reservation", Storage="_Utilisateur", ThisKey="Code", OtherKey="Code", IsForeignKey=true)]
		public Utilisateur Utilisateur
		{
			get
			{
				return this._Utilisateur.Entity;
			}
			set
			{
				Utilisateur previousValue = this._Utilisateur.Entity;
				if (((previousValue != value) 
							|| (this._Utilisateur.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Utilisateur.Entity = null;
						previousValue.Reservations.Remove(this);
					}
					this._Utilisateur.Entity = value;
					if ((value != null))
					{
						value.Reservations.Add(this);
						this._Code = value.Code;
					}
					else
					{
						this._Code = default(string);
					}
					this.SendPropertyChanged("Utilisateur");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Produit_Reservation", Storage="_Produit", ThisKey="CodeProduit", OtherKey="CodeProduit", IsForeignKey=true)]
		public Produit Produit
		{
			get
			{
				return this._Produit.Entity;
			}
			set
			{
				Produit previousValue = this._Produit.Entity;
				if (((previousValue != value) 
							|| (this._Produit.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Produit.Entity = null;
						previousValue.Reservation.Remove(this);
					}
					this._Produit.Entity = value;
					if ((value != null))
					{
						value.Reservation.Add(this);
						this._CodeProduit = value.CodeProduit;
					}
					else
					{
						this._CodeProduit = default(string);
					}
					this.SendPropertyChanged("Produit");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Admin")]
	public partial class Admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CodeAdmin;
		
		private string _Nom;
		
		private string _Prenom;
		
		private string _Rue;
		
		private string _Ville;
		
		private string _Province;
		
		private System.Nullable<int> _Statut;
		
		private string _Photo;
		
		private string _Email;
		
		private System.Nullable<System.DateTime> _DateSuppression;
		
		private string _MotifSuppression;
		
		private System.Nullable<System.DateTime> _DateEmbauche;
		
		private string _password;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeAdminChanging(string value);
    partial void OnCodeAdminChanged();
    partial void OnNomChanging(string value);
    partial void OnNomChanged();
    partial void OnPrenomChanging(string value);
    partial void OnPrenomChanged();
    partial void OnRueChanging(string value);
    partial void OnRueChanged();
    partial void OnVilleChanging(string value);
    partial void OnVilleChanged();
    partial void OnProvinceChanging(string value);
    partial void OnProvinceChanged();
    partial void OnStatutChanging(System.Nullable<int> value);
    partial void OnStatutChanged();
    partial void OnPhotoChanging(string value);
    partial void OnPhotoChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDateSuppressionChanging(System.Nullable<System.DateTime> value);
    partial void OnDateSuppressionChanged();
    partial void OnMotifSuppressionChanging(string value);
    partial void OnMotifSuppressionChanged();
    partial void OnDateEmbaucheChanging(System.Nullable<System.DateTime> value);
    partial void OnDateEmbaucheChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    #endregion
		
		public Admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeAdmin", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodeAdmin
		{
			get
			{
				return this._CodeAdmin;
			}
			set
			{
				if ((this._CodeAdmin != value))
				{
					this.OnCodeAdminChanging(value);
					this.SendPropertyChanging();
					this._CodeAdmin = value;
					this.SendPropertyChanged("CodeAdmin");
					this.OnCodeAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom", DbType="NVarChar(50)")]
		public string Nom
		{
			get
			{
				return this._Nom;
			}
			set
			{
				if ((this._Nom != value))
				{
					this.OnNomChanging(value);
					this.SendPropertyChanging();
					this._Nom = value;
					this.SendPropertyChanged("Nom");
					this.OnNomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prenom", DbType="NVarChar(50)")]
		public string Prenom
		{
			get
			{
				return this._Prenom;
			}
			set
			{
				if ((this._Prenom != value))
				{
					this.OnPrenomChanging(value);
					this.SendPropertyChanging();
					this._Prenom = value;
					this.SendPropertyChanged("Prenom");
					this.OnPrenomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rue", DbType="NVarChar(50)")]
		public string Rue
		{
			get
			{
				return this._Rue;
			}
			set
			{
				if ((this._Rue != value))
				{
					this.OnRueChanging(value);
					this.SendPropertyChanging();
					this._Rue = value;
					this.SendPropertyChanged("Rue");
					this.OnRueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ville", DbType="NVarChar(50)")]
		public string Ville
		{
			get
			{
				return this._Ville;
			}
			set
			{
				if ((this._Ville != value))
				{
					this.OnVilleChanging(value);
					this.SendPropertyChanging();
					this._Ville = value;
					this.SendPropertyChanged("Ville");
					this.OnVilleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Province", DbType="NVarChar(50)")]
		public string Province
		{
			get
			{
				return this._Province;
			}
			set
			{
				if ((this._Province != value))
				{
					this.OnProvinceChanging(value);
					this.SendPropertyChanging();
					this._Province = value;
					this.SendPropertyChanged("Province");
					this.OnProvinceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Statut", DbType="Int")]
		public System.Nullable<int> Statut
		{
			get
			{
				return this._Statut;
			}
			set
			{
				if ((this._Statut != value))
				{
					this.OnStatutChanging(value);
					this.SendPropertyChanging();
					this._Statut = value;
					this.SendPropertyChanged("Statut");
					this.OnStatutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Photo", DbType="NVarChar(50)")]
		public string Photo
		{
			get
			{
				return this._Photo;
			}
			set
			{
				if ((this._Photo != value))
				{
					this.OnPhotoChanging(value);
					this.SendPropertyChanging();
					this._Photo = value;
					this.SendPropertyChanged("Photo");
					this.OnPhotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateSuppression", DbType="Date")]
		public System.Nullable<System.DateTime> DateSuppression
		{
			get
			{
				return this._DateSuppression;
			}
			set
			{
				if ((this._DateSuppression != value))
				{
					this.OnDateSuppressionChanging(value);
					this.SendPropertyChanging();
					this._DateSuppression = value;
					this.SendPropertyChanged("DateSuppression");
					this.OnDateSuppressionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MotifSuppression", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string MotifSuppression
		{
			get
			{
				return this._MotifSuppression;
			}
			set
			{
				if ((this._MotifSuppression != value))
				{
					this.OnMotifSuppressionChanging(value);
					this.SendPropertyChanging();
					this._MotifSuppression = value;
					this.SendPropertyChanged("MotifSuppression");
					this.OnMotifSuppressionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateEmbauche", DbType="Date")]
		public System.Nullable<System.DateTime> DateEmbauche
		{
			get
			{
				return this._DateEmbauche;
			}
			set
			{
				if ((this._DateEmbauche != value))
				{
					this.OnDateEmbaucheChanging(value);
					this.SendPropertyChanging();
					this._DateEmbauche = value;
					this.SendPropertyChanged("DateEmbauche");
					this.OnDateEmbaucheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProduitSupprimes")]
	public partial class ProduitSupprime
	{
		
		private string _CodeProduit;
		
		private string _Nom;
		
		private System.Nullable<double> _PrixAchat;
		
		private System.Nullable<double> _PrixAncien;
		
		private System.Nullable<int> _QuantiteStock;
		
		private string _Photo;
		
		private System.Nullable<decimal> _Note;
		
		private System.Nullable<decimal> _RabaisVente;
		
		private System.Nullable<decimal> _RabaisLocation;
		
		private System.Nullable<System.DateTime> _DateSortie;
		
		private string _Category;
		
		private string _MotifSuppression;
		
		public ProduitSupprime()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeProduit", DbType="NVarChar(50)")]
		public string CodeProduit
		{
			get
			{
				return this._CodeProduit;
			}
			set
			{
				if ((this._CodeProduit != value))
				{
					this._CodeProduit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom", DbType="NVarChar(50)")]
		public string Nom
		{
			get
			{
				return this._Nom;
			}
			set
			{
				if ((this._Nom != value))
				{
					this._Nom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrixAchat", DbType="Float")]
		public System.Nullable<double> PrixAchat
		{
			get
			{
				return this._PrixAchat;
			}
			set
			{
				if ((this._PrixAchat != value))
				{
					this._PrixAchat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrixAncien", DbType="Float")]
		public System.Nullable<double> PrixAncien
		{
			get
			{
				return this._PrixAncien;
			}
			set
			{
				if ((this._PrixAncien != value))
				{
					this._PrixAncien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuantiteStock", DbType="Int")]
		public System.Nullable<int> QuantiteStock
		{
			get
			{
				return this._QuantiteStock;
			}
			set
			{
				if ((this._QuantiteStock != value))
				{
					this._QuantiteStock = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Photo", DbType="NVarChar(50)")]
		public string Photo
		{
			get
			{
				return this._Photo;
			}
			set
			{
				if ((this._Photo != value))
				{
					this._Photo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this._Note = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RabaisVente", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> RabaisVente
		{
			get
			{
				return this._RabaisVente;
			}
			set
			{
				if ((this._RabaisVente != value))
				{
					this._RabaisVente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RabaisLocation", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> RabaisLocation
		{
			get
			{
				return this._RabaisLocation;
			}
			set
			{
				if ((this._RabaisLocation != value))
				{
					this._RabaisLocation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateSortie", DbType="Date")]
		public System.Nullable<System.DateTime> DateSortie
		{
			get
			{
				return this._DateSortie;
			}
			set
			{
				if ((this._DateSortie != value))
				{
					this._DateSortie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="VarChar(MAX)")]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this._Category = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MotifSuppression", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string MotifSuppression
		{
			get
			{
				return this._MotifSuppression;
			}
			set
			{
				if ((this._MotifSuppression != value))
				{
					this._MotifSuppression = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.location")]
	public partial class location : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CodeLocation;
		
		private string _CodeProduit;
		
		private string _Code;
		
		private System.DateTime _DateLocation;
		
		private System.Nullable<System.DateTime> _DateRetour;
		
		private System.Nullable<System.DateTime> _DateRetoureff;
		
		private string _CodeEmployes;
		
		private System.Nullable<double> _PrixLocation;
		
		private System.Nullable<int> _QuantiteLocation;
		
		private System.Nullable<double> _Rabais;
		
		private System.Nullable<double> _Taxe;
		
		private System.Nullable<double> _TotalHT;
		
		private System.Nullable<double> _Ttc;
		
		private System.Nullable<double> _FraisRetard;
		
		private System.Nullable<double> _PenaliteJour;
		
		private string _NomProduit;
		
		private string _NomLocataire;
		
		private EntityRef<Employe> _Employe;
		
		private EntityRef<Utilisateur> _Utilisateur;
		
		private EntityRef<Produit> _Produit;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeLocationChanging(string value);
    partial void OnCodeLocationChanged();
    partial void OnCodeProduitChanging(string value);
    partial void OnCodeProduitChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnDateLocationChanging(System.DateTime value);
    partial void OnDateLocationChanged();
    partial void OnDateRetourChanging(System.Nullable<System.DateTime> value);
    partial void OnDateRetourChanged();
    partial void OnDateRetoureffChanging(System.Nullable<System.DateTime> value);
    partial void OnDateRetoureffChanged();
    partial void OnCodeEmployesChanging(string value);
    partial void OnCodeEmployesChanged();
    partial void OnPrixLocationChanging(System.Nullable<double> value);
    partial void OnPrixLocationChanged();
    partial void OnQuantiteLocationChanging(System.Nullable<int> value);
    partial void OnQuantiteLocationChanged();
    partial void OnRabaisChanging(System.Nullable<double> value);
    partial void OnRabaisChanged();
    partial void OnTaxeChanging(System.Nullable<double> value);
    partial void OnTaxeChanged();
    partial void OnTotalHTChanging(System.Nullable<double> value);
    partial void OnTotalHTChanged();
    partial void OnTtcChanging(System.Nullable<double> value);
    partial void OnTtcChanged();
    partial void OnFraisRetardChanging(System.Nullable<double> value);
    partial void OnFraisRetardChanged();
    partial void OnPenaliteJourChanging(System.Nullable<double> value);
    partial void OnPenaliteJourChanged();
    partial void OnNomProduitChanging(string value);
    partial void OnNomProduitChanged();
    partial void OnNomLocataireChanging(string value);
    partial void OnNomLocataireChanged();
    #endregion
		
		public location()
		{
			this._Employe = default(EntityRef<Employe>);
			this._Utilisateur = default(EntityRef<Utilisateur>);
			this._Produit = default(EntityRef<Produit>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeLocation", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodeLocation
		{
			get
			{
				return this._CodeLocation;
			}
			set
			{
				if ((this._CodeLocation != value))
				{
					this.OnCodeLocationChanging(value);
					this.SendPropertyChanging();
					this._CodeLocation = value;
					this.SendPropertyChanged("CodeLocation");
					this.OnCodeLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeProduit", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodeProduit
		{
			get
			{
				return this._CodeProduit;
			}
			set
			{
				if ((this._CodeProduit != value))
				{
					if (this._Produit.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodeProduitChanging(value);
					this.SendPropertyChanging();
					this._CodeProduit = value;
					this.SendPropertyChanged("CodeProduit");
					this.OnCodeProduitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					if (this._Utilisateur.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateLocation", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime DateLocation
		{
			get
			{
				return this._DateLocation;
			}
			set
			{
				if ((this._DateLocation != value))
				{
					this.OnDateLocationChanging(value);
					this.SendPropertyChanging();
					this._DateLocation = value;
					this.SendPropertyChanged("DateLocation");
					this.OnDateLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateRetour", DbType="Date")]
		public System.Nullable<System.DateTime> DateRetour
		{
			get
			{
				return this._DateRetour;
			}
			set
			{
				if ((this._DateRetour != value))
				{
					this.OnDateRetourChanging(value);
					this.SendPropertyChanging();
					this._DateRetour = value;
					this.SendPropertyChanged("DateRetour");
					this.OnDateRetourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateRetoureff", DbType="Date")]
		public System.Nullable<System.DateTime> DateRetoureff
		{
			get
			{
				return this._DateRetoureff;
			}
			set
			{
				if ((this._DateRetoureff != value))
				{
					this.OnDateRetoureffChanging(value);
					this.SendPropertyChanging();
					this._DateRetoureff = value;
					this.SendPropertyChanged("DateRetoureff");
					this.OnDateRetoureffChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeEmployes", DbType="NVarChar(50)")]
		public string CodeEmployes
		{
			get
			{
				return this._CodeEmployes;
			}
			set
			{
				if ((this._CodeEmployes != value))
				{
					if (this._Employe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodeEmployesChanging(value);
					this.SendPropertyChanging();
					this._CodeEmployes = value;
					this.SendPropertyChanged("CodeEmployes");
					this.OnCodeEmployesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrixLocation", DbType="Float")]
		public System.Nullable<double> PrixLocation
		{
			get
			{
				return this._PrixLocation;
			}
			set
			{
				if ((this._PrixLocation != value))
				{
					this.OnPrixLocationChanging(value);
					this.SendPropertyChanging();
					this._PrixLocation = value;
					this.SendPropertyChanged("PrixLocation");
					this.OnPrixLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuantiteLocation", DbType="Int")]
		public System.Nullable<int> QuantiteLocation
		{
			get
			{
				return this._QuantiteLocation;
			}
			set
			{
				if ((this._QuantiteLocation != value))
				{
					this.OnQuantiteLocationChanging(value);
					this.SendPropertyChanging();
					this._QuantiteLocation = value;
					this.SendPropertyChanged("QuantiteLocation");
					this.OnQuantiteLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rabais", DbType="Float")]
		public System.Nullable<double> Rabais
		{
			get
			{
				return this._Rabais;
			}
			set
			{
				if ((this._Rabais != value))
				{
					this.OnRabaisChanging(value);
					this.SendPropertyChanging();
					this._Rabais = value;
					this.SendPropertyChanged("Rabais");
					this.OnRabaisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Taxe", DbType="Float")]
		public System.Nullable<double> Taxe
		{
			get
			{
				return this._Taxe;
			}
			set
			{
				if ((this._Taxe != value))
				{
					this.OnTaxeChanging(value);
					this.SendPropertyChanging();
					this._Taxe = value;
					this.SendPropertyChanged("Taxe");
					this.OnTaxeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalHT", DbType="Float")]
		public System.Nullable<double> TotalHT
		{
			get
			{
				return this._TotalHT;
			}
			set
			{
				if ((this._TotalHT != value))
				{
					this.OnTotalHTChanging(value);
					this.SendPropertyChanging();
					this._TotalHT = value;
					this.SendPropertyChanged("TotalHT");
					this.OnTotalHTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ttc", DbType="Float")]
		public System.Nullable<double> Ttc
		{
			get
			{
				return this._Ttc;
			}
			set
			{
				if ((this._Ttc != value))
				{
					this.OnTtcChanging(value);
					this.SendPropertyChanging();
					this._Ttc = value;
					this.SendPropertyChanged("Ttc");
					this.OnTtcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FraisRetard", DbType="Float")]
		public System.Nullable<double> FraisRetard
		{
			get
			{
				return this._FraisRetard;
			}
			set
			{
				if ((this._FraisRetard != value))
				{
					this.OnFraisRetardChanging(value);
					this.SendPropertyChanging();
					this._FraisRetard = value;
					this.SendPropertyChanged("FraisRetard");
					this.OnFraisRetardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PenaliteJour", DbType="Float")]
		public System.Nullable<double> PenaliteJour
		{
			get
			{
				return this._PenaliteJour;
			}
			set
			{
				if ((this._PenaliteJour != value))
				{
					this.OnPenaliteJourChanging(value);
					this.SendPropertyChanging();
					this._PenaliteJour = value;
					this.SendPropertyChanged("PenaliteJour");
					this.OnPenaliteJourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomProduit", DbType="NVarChar(53)")]
		public string NomProduit
		{
			get
			{
				return this._NomProduit;
			}
			set
			{
				if ((this._NomProduit != value))
				{
					this.OnNomProduitChanging(value);
					this.SendPropertyChanging();
					this._NomProduit = value;
					this.SendPropertyChanged("NomProduit");
					this.OnNomProduitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomLocataire", DbType="NVarChar(53)")]
		public string NomLocataire
		{
			get
			{
				return this._NomLocataire;
			}
			set
			{
				if ((this._NomLocataire != value))
				{
					this.OnNomLocataireChanging(value);
					this.SendPropertyChanging();
					this._NomLocataire = value;
					this.SendPropertyChanged("NomLocataire");
					this.OnNomLocataireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Employe_location", Storage="_Employe", ThisKey="CodeEmployes", OtherKey="CodeEmployes", IsForeignKey=true)]
		public Employe Employe
		{
			get
			{
				return this._Employe.Entity;
			}
			set
			{
				Employe previousValue = this._Employe.Entity;
				if (((previousValue != value) 
							|| (this._Employe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Employe.Entity = null;
						previousValue.location.Remove(this);
					}
					this._Employe.Entity = value;
					if ((value != null))
					{
						value.location.Add(this);
						this._CodeEmployes = value.CodeEmployes;
					}
					else
					{
						this._CodeEmployes = default(string);
					}
					this.SendPropertyChanged("Employe");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Utilisateur_location", Storage="_Utilisateur", ThisKey="Code", OtherKey="Code", IsForeignKey=true)]
		public Utilisateur Utilisateur
		{
			get
			{
				return this._Utilisateur.Entity;
			}
			set
			{
				Utilisateur previousValue = this._Utilisateur.Entity;
				if (((previousValue != value) 
							|| (this._Utilisateur.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Utilisateur.Entity = null;
						previousValue.location.Remove(this);
					}
					this._Utilisateur.Entity = value;
					if ((value != null))
					{
						value.location.Add(this);
						this._Code = value.Code;
					}
					else
					{
						this._Code = default(string);
					}
					this.SendPropertyChanged("Utilisateur");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Produit_location", Storage="_Produit", ThisKey="CodeProduit", OtherKey="CodeProduit", IsForeignKey=true)]
		public Produit Produit
		{
			get
			{
				return this._Produit.Entity;
			}
			set
			{
				Produit previousValue = this._Produit.Entity;
				if (((previousValue != value) 
							|| (this._Produit.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Produit.Entity = null;
						previousValue.location.Remove(this);
					}
					this._Produit.Entity = value;
					if ((value != null))
					{
						value.location.Add(this);
						this._CodeProduit = value.CodeProduit;
					}
					else
					{
						this._CodeProduit = default(string);
					}
					this.SendPropertyChanged("Produit");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Produit")]
	public partial class Produit : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CodeProduit;
		
		private string _Nom;
		
		private System.Nullable<double> _PrixAchat;
		
		private System.Nullable<double> _PrixAncien;
		
		private System.Nullable<double> _PrixLoc;
		
		private System.Nullable<int> _QuantiteStock;
		
		private string _Photo;
		
		private System.Nullable<decimal> _Note;
		
		private System.Nullable<decimal> _RabaisVente;
		
		private System.Nullable<decimal> _RabaisLocation;
		
		private System.Nullable<System.DateTime> _DateSortie;
		
		private string _Category;
		
		private string _MotifSuppression;
		
		private string _Desc;
		
		private EntitySet<Reservation> _Reservation;
		
		private EntitySet<location> _location;
		
		private EntitySet<Vente> _Vente;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeProduitChanging(string value);
    partial void OnCodeProduitChanged();
    partial void OnNomChanging(string value);
    partial void OnNomChanged();
    partial void OnPrixAchatChanging(System.Nullable<double> value);
    partial void OnPrixAchatChanged();
    partial void OnPrixAncienChanging(System.Nullable<double> value);
    partial void OnPrixAncienChanged();
    partial void OnPrixLocChanging(System.Nullable<double> value);
    partial void OnPrixLocChanged();
    partial void OnQuantiteStockChanging(System.Nullable<int> value);
    partial void OnQuantiteStockChanged();
    partial void OnPhotoChanging(string value);
    partial void OnPhotoChanged();
    partial void OnNoteChanging(System.Nullable<decimal> value);
    partial void OnNoteChanged();
    partial void OnRabaisVenteChanging(System.Nullable<decimal> value);
    partial void OnRabaisVenteChanged();
    partial void OnRabaisLocationChanging(System.Nullable<decimal> value);
    partial void OnRabaisLocationChanged();
    partial void OnDateSortieChanging(System.Nullable<System.DateTime> value);
    partial void OnDateSortieChanged();
    partial void OnCategoryChanging(string value);
    partial void OnCategoryChanged();
    partial void OnMotifSuppressionChanging(string value);
    partial void OnMotifSuppressionChanged();
    partial void OnDescChanging(string value);
    partial void OnDescChanged();
    #endregion
		
		public Produit()
		{
			this._Reservation = new EntitySet<Reservation>(new Action<Reservation>(this.attach_Reservation), new Action<Reservation>(this.detach_Reservation));
			this._location = new EntitySet<location>(new Action<location>(this.attach_location), new Action<location>(this.detach_location));
			this._Vente = new EntitySet<Vente>(new Action<Vente>(this.attach_Vente), new Action<Vente>(this.detach_Vente));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeProduit", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodeProduit
		{
			get
			{
				return this._CodeProduit;
			}
			set
			{
				if ((this._CodeProduit != value))
				{
					this.OnCodeProduitChanging(value);
					this.SendPropertyChanging();
					this._CodeProduit = value;
					this.SendPropertyChanged("CodeProduit");
					this.OnCodeProduitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom", DbType="NVarChar(50)")]
		public string Nom
		{
			get
			{
				return this._Nom;
			}
			set
			{
				if ((this._Nom != value))
				{
					this.OnNomChanging(value);
					this.SendPropertyChanging();
					this._Nom = value;
					this.SendPropertyChanged("Nom");
					this.OnNomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrixAchat", DbType="Float")]
		public System.Nullable<double> PrixAchat
		{
			get
			{
				return this._PrixAchat;
			}
			set
			{
				if ((this._PrixAchat != value))
				{
					this.OnPrixAchatChanging(value);
					this.SendPropertyChanging();
					this._PrixAchat = value;
					this.SendPropertyChanged("PrixAchat");
					this.OnPrixAchatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrixAncien", DbType="Float")]
		public System.Nullable<double> PrixAncien
		{
			get
			{
				return this._PrixAncien;
			}
			set
			{
				if ((this._PrixAncien != value))
				{
					this.OnPrixAncienChanging(value);
					this.SendPropertyChanging();
					this._PrixAncien = value;
					this.SendPropertyChanged("PrixAncien");
					this.OnPrixAncienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrixLoc", DbType="Float")]
		public System.Nullable<double> PrixLoc
		{
			get
			{
				return this._PrixLoc;
			}
			set
			{
				if ((this._PrixLoc != value))
				{
					this.OnPrixLocChanging(value);
					this.SendPropertyChanging();
					this._PrixLoc = value;
					this.SendPropertyChanged("PrixLoc");
					this.OnPrixLocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuantiteStock", DbType="Int")]
		public System.Nullable<int> QuantiteStock
		{
			get
			{
				return this._QuantiteStock;
			}
			set
			{
				if ((this._QuantiteStock != value))
				{
					this.OnQuantiteStockChanging(value);
					this.SendPropertyChanging();
					this._QuantiteStock = value;
					this.SendPropertyChanged("QuantiteStock");
					this.OnQuantiteStockChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Photo", DbType="NVarChar(50)")]
		public string Photo
		{
			get
			{
				return this._Photo;
			}
			set
			{
				if ((this._Photo != value))
				{
					this.OnPhotoChanging(value);
					this.SendPropertyChanging();
					this._Photo = value;
					this.SendPropertyChanged("Photo");
					this.OnPhotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this.OnNoteChanging(value);
					this.SendPropertyChanging();
					this._Note = value;
					this.SendPropertyChanged("Note");
					this.OnNoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RabaisVente", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> RabaisVente
		{
			get
			{
				return this._RabaisVente;
			}
			set
			{
				if ((this._RabaisVente != value))
				{
					this.OnRabaisVenteChanging(value);
					this.SendPropertyChanging();
					this._RabaisVente = value;
					this.SendPropertyChanged("RabaisVente");
					this.OnRabaisVenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RabaisLocation", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> RabaisLocation
		{
			get
			{
				return this._RabaisLocation;
			}
			set
			{
				if ((this._RabaisLocation != value))
				{
					this.OnRabaisLocationChanging(value);
					this.SendPropertyChanging();
					this._RabaisLocation = value;
					this.SendPropertyChanged("RabaisLocation");
					this.OnRabaisLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateSortie", DbType="Date")]
		public System.Nullable<System.DateTime> DateSortie
		{
			get
			{
				return this._DateSortie;
			}
			set
			{
				if ((this._DateSortie != value))
				{
					this.OnDateSortieChanging(value);
					this.SendPropertyChanging();
					this._DateSortie = value;
					this.SendPropertyChanged("DateSortie");
					this.OnDateSortieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="VarChar(MAX)")]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this.OnCategoryChanging(value);
					this.SendPropertyChanging();
					this._Category = value;
					this.SendPropertyChanged("Category");
					this.OnCategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MotifSuppression", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string MotifSuppression
		{
			get
			{
				return this._MotifSuppression;
			}
			set
			{
				if ((this._MotifSuppression != value))
				{
					this.OnMotifSuppressionChanging(value);
					this.SendPropertyChanging();
					this._MotifSuppression = value;
					this.SendPropertyChanged("MotifSuppression");
					this.OnMotifSuppressionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Desc]", Storage="_Desc", DbType="NVarChar(100)")]
		public string Desc
		{
			get
			{
				return this._Desc;
			}
			set
			{
				if ((this._Desc != value))
				{
					this.OnDescChanging(value);
					this.SendPropertyChanging();
					this._Desc = value;
					this.SendPropertyChanged("Desc");
					this.OnDescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Produit_Reservation", Storage="_Reservation", ThisKey="CodeProduit", OtherKey="CodeProduit")]
		public EntitySet<Reservation> Reservation
		{
			get
			{
				return this._Reservation;
			}
			set
			{
				this._Reservation.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Produit_location", Storage="_location", ThisKey="CodeProduit", OtherKey="CodeProduit")]
		public EntitySet<location> location
		{
			get
			{
				return this._location;
			}
			set
			{
				this._location.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Produit_Vente", Storage="_Vente", ThisKey="CodeProduit", OtherKey="CodeProduit")]
		public EntitySet<Vente> Vente
		{
			get
			{
				return this._Vente;
			}
			set
			{
				this._Vente.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Reservation(Reservation entity)
		{
			this.SendPropertyChanging();
			entity.Produit = this;
		}
		
		private void detach_Reservation(Reservation entity)
		{
			this.SendPropertyChanging();
			entity.Produit = null;
		}
		
		private void attach_location(location entity)
		{
			this.SendPropertyChanging();
			entity.Produit = this;
		}
		
		private void detach_location(location entity)
		{
			this.SendPropertyChanging();
			entity.Produit = null;
		}
		
		private void attach_Vente(Vente entity)
		{
			this.SendPropertyChanging();
			entity.Produit = this;
		}
		
		private void detach_Vente(Vente entity)
		{
			this.SendPropertyChanging();
			entity.Produit = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vente")]
	public partial class Vente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdVente;
		
		private string _CodeProduit;
		
		private string _Code;
		
		private System.DateTime _DateVente;
		
		private string _CodeEmployes;
		
		private System.Nullable<double> _PrixVente;
		
		private System.Nullable<int> _QuantiteVente;
		
		private System.Nullable<float> _Rabais;
		
		private System.Nullable<double> _Taxe;
		
		private System.Nullable<double> _TotalHT;
		
		private System.Nullable<double> _Ttc;
		
		private string _NomProduit;
		
		private string _NomMembre;
		
		private System.Nullable<double> _Montant;
		
		private System.Nullable<int> _StatutP;
		
		private EntityRef<Produit> _Produit;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdVenteChanging(string value);
    partial void OnIdVenteChanged();
    partial void OnCodeProduitChanging(string value);
    partial void OnCodeProduitChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnDateVenteChanging(System.DateTime value);
    partial void OnDateVenteChanged();
    partial void OnCodeEmployesChanging(string value);
    partial void OnCodeEmployesChanged();
    partial void OnPrixVenteChanging(System.Nullable<double> value);
    partial void OnPrixVenteChanged();
    partial void OnQuantiteVenteChanging(System.Nullable<int> value);
    partial void OnQuantiteVenteChanged();
    partial void OnRabaisChanging(System.Nullable<float> value);
    partial void OnRabaisChanged();
    partial void OnTaxeChanging(System.Nullable<double> value);
    partial void OnTaxeChanged();
    partial void OnTotalHTChanging(System.Nullable<double> value);
    partial void OnTotalHTChanged();
    partial void OnTtcChanging(System.Nullable<double> value);
    partial void OnTtcChanged();
    partial void OnNomProduitChanging(string value);
    partial void OnNomProduitChanged();
    partial void OnNomMembreChanging(string value);
    partial void OnNomMembreChanged();
    partial void OnMontantChanging(System.Nullable<double> value);
    partial void OnMontantChanged();
    partial void OnStatutPChanging(System.Nullable<int> value);
    partial void OnStatutPChanged();
    #endregion
		
		public Vente()
		{
			this._Produit = default(EntityRef<Produit>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdVente", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdVente
		{
			get
			{
				return this._IdVente;
			}
			set
			{
				if ((this._IdVente != value))
				{
					this.OnIdVenteChanging(value);
					this.SendPropertyChanging();
					this._IdVente = value;
					this.SendPropertyChanged("IdVente");
					this.OnIdVenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeProduit", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodeProduit
		{
			get
			{
				return this._CodeProduit;
			}
			set
			{
				if ((this._CodeProduit != value))
				{
					if (this._Produit.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodeProduitChanging(value);
					this.SendPropertyChanging();
					this._CodeProduit = value;
					this.SendPropertyChanged("CodeProduit");
					this.OnCodeProduitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateVente", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime DateVente
		{
			get
			{
				return this._DateVente;
			}
			set
			{
				if ((this._DateVente != value))
				{
					this.OnDateVenteChanging(value);
					this.SendPropertyChanging();
					this._DateVente = value;
					this.SendPropertyChanged("DateVente");
					this.OnDateVenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeEmployes", DbType="NVarChar(50)")]
		public string CodeEmployes
		{
			get
			{
				return this._CodeEmployes;
			}
			set
			{
				if ((this._CodeEmployes != value))
				{
					this.OnCodeEmployesChanging(value);
					this.SendPropertyChanging();
					this._CodeEmployes = value;
					this.SendPropertyChanged("CodeEmployes");
					this.OnCodeEmployesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrixVente", DbType="Float")]
		public System.Nullable<double> PrixVente
		{
			get
			{
				return this._PrixVente;
			}
			set
			{
				if ((this._PrixVente != value))
				{
					this.OnPrixVenteChanging(value);
					this.SendPropertyChanging();
					this._PrixVente = value;
					this.SendPropertyChanged("PrixVente");
					this.OnPrixVenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuantiteVente", DbType="Int")]
		public System.Nullable<int> QuantiteVente
		{
			get
			{
				return this._QuantiteVente;
			}
			set
			{
				if ((this._QuantiteVente != value))
				{
					this.OnQuantiteVenteChanging(value);
					this.SendPropertyChanging();
					this._QuantiteVente = value;
					this.SendPropertyChanged("QuantiteVente");
					this.OnQuantiteVenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rabais", DbType="Real")]
		public System.Nullable<float> Rabais
		{
			get
			{
				return this._Rabais;
			}
			set
			{
				if ((this._Rabais != value))
				{
					this.OnRabaisChanging(value);
					this.SendPropertyChanging();
					this._Rabais = value;
					this.SendPropertyChanged("Rabais");
					this.OnRabaisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Taxe", DbType="Float")]
		public System.Nullable<double> Taxe
		{
			get
			{
				return this._Taxe;
			}
			set
			{
				if ((this._Taxe != value))
				{
					this.OnTaxeChanging(value);
					this.SendPropertyChanging();
					this._Taxe = value;
					this.SendPropertyChanged("Taxe");
					this.OnTaxeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalHT", DbType="Float")]
		public System.Nullable<double> TotalHT
		{
			get
			{
				return this._TotalHT;
			}
			set
			{
				if ((this._TotalHT != value))
				{
					this.OnTotalHTChanging(value);
					this.SendPropertyChanging();
					this._TotalHT = value;
					this.SendPropertyChanged("TotalHT");
					this.OnTotalHTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ttc", DbType="Float")]
		public System.Nullable<double> Ttc
		{
			get
			{
				return this._Ttc;
			}
			set
			{
				if ((this._Ttc != value))
				{
					this.OnTtcChanging(value);
					this.SendPropertyChanging();
					this._Ttc = value;
					this.SendPropertyChanged("Ttc");
					this.OnTtcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomProduit", DbType="NVarChar(53)")]
		public string NomProduit
		{
			get
			{
				return this._NomProduit;
			}
			set
			{
				if ((this._NomProduit != value))
				{
					this.OnNomProduitChanging(value);
					this.SendPropertyChanging();
					this._NomProduit = value;
					this.SendPropertyChanged("NomProduit");
					this.OnNomProduitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomMembre", DbType="NVarChar(53)")]
		public string NomMembre
		{
			get
			{
				return this._NomMembre;
			}
			set
			{
				if ((this._NomMembre != value))
				{
					this.OnNomMembreChanging(value);
					this.SendPropertyChanging();
					this._NomMembre = value;
					this.SendPropertyChanged("NomMembre");
					this.OnNomMembreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Montant", DbType="Float")]
		public System.Nullable<double> Montant
		{
			get
			{
				return this._Montant;
			}
			set
			{
				if ((this._Montant != value))
				{
					this.OnMontantChanging(value);
					this.SendPropertyChanging();
					this._Montant = value;
					this.SendPropertyChanged("Montant");
					this.OnMontantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatutP", DbType="Int")]
		public System.Nullable<int> StatutP
		{
			get
			{
				return this._StatutP;
			}
			set
			{
				if ((this._StatutP != value))
				{
					this.OnStatutPChanging(value);
					this.SendPropertyChanging();
					this._StatutP = value;
					this.SendPropertyChanged("StatutP");
					this.OnStatutPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Produit_Vente", Storage="_Produit", ThisKey="CodeProduit", OtherKey="CodeProduit", IsForeignKey=true)]
		public Produit Produit
		{
			get
			{
				return this._Produit.Entity;
			}
			set
			{
				Produit previousValue = this._Produit.Entity;
				if (((previousValue != value) 
							|| (this._Produit.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Produit.Entity = null;
						previousValue.Vente.Remove(this);
					}
					this._Produit.Entity = value;
					if ((value != null))
					{
						value.Vente.Add(this);
						this._CodeProduit = value.CodeProduit;
					}
					else
					{
						this._CodeProduit = default(string);
					}
					this.SendPropertyChanged("Produit");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
